//Add or Delete the vendors which are not to be included in bundle
module.exports =  {
    'react': 'react',
    'react-router': 'reactRouter',
    'react-dom': 'reactDom',
    'object-assign': 'objectAssign',
    'phrontend': 'phrontend',
    'classnames': 'classnames',
    'keymirror': 'keymirror',
    'flux': 'flux',
    'lodash.isstring': 'lodashIsstring',
    'lodash.isarray': 'lodashIsarray',
    'lodash.isundefined': 'lodashIsundefined',
    'lodash.result': 'lodashResult',
    'lodash.clone': 'lodashClone',
    'es6-promise': 'es6Promise',
    'form-serialize': 'formSerialize',
    'lodash._baseclone': 'lodashBaseclone',
    'lodash.keys': 'lodashKeys',
    'lodash.isarguments': 'lodashIsarguments',
    'process': 'process',
    'object.assign': 'objectAssign1',
    'object-keys': 'objectKeys',
};
